Add test for default value on 'get'
sindresorhus/dot-prop pull request #72
Opened 2020-10-15 15:56 UTC by saibotsivad

This is to show the breaking test from #71 which is an open question still.

If there's a change that comes out of that issue, I will try to update this PR with the change, otherwise it can be closed.

2020-10-15 15:58 UTC, saibotsivad commented
(Note that tests are currently expected to fail, as per discussion in #71 )

2020-11-01 20:32 UTC, Afsaneh5054 approved these changes

2020-11-01 20:39 UTC, Afsaneh5054 approved these changes

2020-12-08 01:08 UTC, shehrozkhan88 requested changes
saibotsivad:master

2020-12-19 16:23 UTC, sindresorhus commented
Per https://github.com/sindresorhus/dot-prop/issues/71#issuecomment-711389255, it will need a lot more tests and also docs and TS types updates. If you're interested in submitting that, go ahead and open a new PR. But this PR is not mergeable as-is.

2020-12-19 16:23 UTC, closed without merging